table Product
	lineageTag: 58b3994f-5373-4187-b920-3712d0d1dfde

	column product_key
		dataType: string
		lineageTag: ee3dfbf2-dc00-4bd9-81b9-dbb65380f79e
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column product_level_1
		dataType: string
		lineageTag: 08016fcd-3bad-4f89-8894-2c6dca004340
		summarizeBy: none
		sourceColumn: product_level_1

		annotation SummarizationSetBy = Automatic

	column product_level_2
		dataType: string
		lineageTag: 8f696464-e398-4c5f-9b52-7afba1d5cc75
		summarizeBy: none
		sourceColumn: product_level_2

		annotation SummarizationSetBy = Automatic

	column revenue_type
		dataType: int64
		formatString: 0
		lineageTag: 2fa228ff-8ecd-4d5f-86a4-241f405e1603
		summarizeBy: none
		sourceColumn: revenue_type

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\VenkataRishitha\Training\CRB\Product.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_key", type text}, {"product_level_1", type text}, {"product_level_2", type text}, {"revenue_type", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

