table results
	lineageTag: a03cd918-7073-4758-af50-c983be57e0ea

	column Month_start
		dataType: dateTime
		formatString: Long Date
		lineageTag: c5ef6dc9-e335-4ed8-b45a-7248818d99a2
		summarizeBy: none
		sourceColumn: Month_start

		variation Variation
			isDefault
			relationship: 8b92764d-3a23-4d9c-885e-46c0d85e31f1
			defaultHierarchy: LocalDateTable_01dbfec7-6126-4e83-9c3b-6cf5a143ef76.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Period_type
		dataType: string
		lineageTag: db5dda22-ac2d-4f1e-afd3-2e7596f495e2
		summarizeBy: none
		sourceColumn: Period_type

		annotation SummarizationSetBy = Automatic

	column BOP
		dataType: double
		lineageTag: ef92394a-4267-46a1-b839-80715e4dc108
		summarizeBy: sum
		sourceColumn: BOP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Churn '
		dataType: double
		lineageTag: a282396e-0a4d-4642-b6d2-aaaa011273a1
		summarizeBy: sum
		sourceColumn: "Churn "

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Churn_Percent
		dataType: double
		lineageTag: 2449d319-0595-4f77-b6b4-54e33f43b048
		summarizeBy: sum
		sourceColumn: Churn_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Downsell
		dataType: double
		lineageTag: 362198bc-496f-432d-bc5e-94864f746781
		summarizeBy: sum
		sourceColumn: Downsell

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Downsell_Percent
		dataType: double
		lineageTag: 2a79e1f9-dec3-4d66-bc31-0fec27377d3b
		summarizeBy: sum
		sourceColumn: Downsell_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Downgrade
		dataType: double
		lineageTag: 1d06058f-74d9-44e4-b429-40d0ec06a337
		summarizeBy: sum
		sourceColumn: Downgrade

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Downgrade_Percent
		dataType: double
		lineageTag: f904f9cf-e740-45cb-80b3-c483736b6ca1
		summarizeBy: sum
		sourceColumn: Downgrade_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GRR
		dataType: double
		lineageTag: 421d1190-aba7-4c46-88f3-f6acb53e00af
		summarizeBy: sum
		sourceColumn: GRR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GRR_Percent
		dataType: double
		lineageTag: 51657de7-be7f-4a13-9da7-9fba7b994dce
		summarizeBy: sum
		sourceColumn: GRR_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Upsell
		dataType: double
		lineageTag: bd14b2ac-00de-4548-a7b8-b71b9bb9c8cf
		summarizeBy: sum
		sourceColumn: Upsell

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Upsell_Percent
		dataType: double
		lineageTag: 358a685f-669f-4d3b-94e9-0814eda96b47
		summarizeBy: sum
		sourceColumn: Upsell_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cross_Sell
		dataType: double
		lineageTag: a51ece73-e4dd-4b36-ae5c-401959af2f42
		summarizeBy: sum
		sourceColumn: Cross_Sell

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cross_Sell_Percent
		dataType: double
		lineageTag: 33628da4-0a21-4a92-bd37-00d47f34507c
		summarizeBy: sum
		sourceColumn: Cross_Sell_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NRR
		dataType: double
		lineageTag: 6e15864b-71d2-4e18-bf68-d30e39aba851
		summarizeBy: sum
		sourceColumn: NRR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NRR_Percent
		dataType: double
		lineageTag: c9a3fd4e-deff-4e46-867e-4b88bd8fe3d8
		summarizeBy: sum
		sourceColumn: NRR_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column New_Organic
		dataType: double
		lineageTag: 56b35a61-d344-4bc1-8334-385e12701f74
		summarizeBy: sum
		sourceColumn: New_Organic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column New_Organic_Percent
		dataType: double
		lineageTag: 299167a8-ec2d-4a65-bff6-f732cadee3db
		summarizeBy: sum
		sourceColumn: New_Organic_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EOP
		dataType: double
		lineageTag: 8776021a-3d7d-419e-ba69-9c526059cebe
		summarizeBy: sum
		sourceColumn: EOP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EOP_Percent
		dataType: double
		lineageTag: f58ca618-375b-4029-a974-fe3e6fe1be4e
		summarizeBy: sum
		sourceColumn: EOP_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition results = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\VenkataRishitha\Documents\results.csv"),[Delimiter=",", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Month_start", type date}, {"Period_type", type text}, {"BOP", type number}, {"Churn ", type number}, {"Churn_Percent", type number}, {"Downsell", type number}, {"Downsell_Percent", type number}, {"Downgrade", type number}, {"Downgrade_Percent", type number}, {"GRR", type number}, {"GRR_Percent", type number}, {"Upsell", type number}, {"Upsell_Percent", type number}, {"Cross_Sell", type number}, {"Cross_Sell_Percent", type number}, {"NRR", type number}, {"NRR_Percent", type number}, {"New_Organic", type number}, {"New_Organic_Percent", type number}, {"EOP", type number}, {"EOP_Percent", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

