table snowball_output
	lineageTag: fbe967ef-c25a-4e77-b4be-3f5d2ad6c651

	column snowball_key
		dataType: string
		lineageTag: 988dc6b9-1530-4f5a-b30f-88fcf1f7cffe
		summarizeBy: none
		sourceColumn: snowball_key

		annotation SummarizationSetBy = Automatic

	column customer_key
		dataType: string
		lineageTag: ef62f3fc-f03d-4079-8f7b-1f0c02965a91
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: string
		lineageTag: 76a5ed04-c17e-4b1f-aab0-c8e2856a6e93
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column month_roll
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3da23dc7-dbeb-485e-847b-b516636ca77f
		summarizeBy: none
		sourceColumn: month_roll

		variation Variation
			isDefault
			relationship: 25e3ca04-bb87-4fbb-aa3b-c015b414abd3
			defaultHierarchy: LocalDateTable_481e1f75-2945-4e48-8d2c-a06c8bd459bf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column period_type
		dataType: string
		lineageTag: 06ac6cd9-15cb-4e9a-b3bf-597bf15b2a10
		summarizeBy: none
		sourceColumn: period_type

		annotation SummarizationSetBy = Automatic

	column bop_arr
		dataType: double
		lineageTag: 6cfb0658-c13f-4929-a9ac-44786b0d0b25
		summarizeBy: sum
		sourceColumn: bop_arr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_churn
		dataType: double
		lineageTag: 4a750161-9e5c-435e-9b6a-0aea102b5500
		summarizeBy: sum
		sourceColumn: customer_churn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_churn
		dataType: double
		lineageTag: 36a8ce57-6b1f-431b-8a9e-9c845c0aadb9
		summarizeBy: sum
		sourceColumn: product_churn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column downsell
		dataType: double
		lineageTag: c165c6bc-bb95-4ddf-8e59-23b4ae651a4b
		summarizeBy: sum
		sourceColumn: downsell

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grr
		dataType: double
		lineageTag: b2cfa991-2617-492c-9e0d-cc55aef0f739
		summarizeBy: sum
		sourceColumn: grr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column upsell
		dataType: double
		lineageTag: 03617316-8c41-4bcb-9c86-7d9e44955135
		summarizeBy: sum
		sourceColumn: upsell

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cross_sell
		dataType: int64
		formatString: 0
		lineageTag: fe976d0f-f488-4bbd-845a-f00125d6b191
		summarizeBy: sum
		sourceColumn: cross_sell

		annotation SummarizationSetBy = Automatic

	column nrr
		dataType: double
		lineageTag: d653df60-6495-4c14-ae5d-36c88710728e
		summarizeBy: sum
		sourceColumn: nrr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_customer
		dataType: double
		lineageTag: 2f89ffaa-abe7-4a1c-b886-a191e6d8ec49
		summarizeBy: sum
		sourceColumn: new_customer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column eop_arr
		dataType: double
		lineageTag: 2a2dd13b-ab6a-4b6e-bb6d-6f8aee2d6afd
		summarizeBy: sum
		sourceColumn: eop_arr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition snowball_output = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\VenkataRishitha\Training\CRB\snowball_output.csv"),[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"snowball_key", type text}, {"customer_key", type text}, {"product_key", type text}, {"month_roll", type date}, {"period_type", type text}, {"bop_arr", type number}, {"customer_churn", type number}, {"product_churn", type number}, {"downsell", type number}, {"grr", type number}, {"upsell", type number}, {"cross_sell", Int64.Type}, {"nrr", type number}, {"new_customer", type number}, {"eop_arr", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

